### ISSUE TITLE
Update the title element value in index.html

### ISSUE THREAD

**Issue by JamesGable** [LearningNerd/seeplay#1]
@LearningNerd Yay, the SeePlay app works! I tested the app using my Android phone as a MIDI Device and the app functions as expected :)

I did find one minor accessibility concern.

You need to update the title element value in index.html. While the current title "Hello!" is  friendly and welcoming, a different title value that describes the page's purpose would be better :)

**Comment by LearningNerd** [comment]
Ooooh I'm so glad to hear it works on your phone! I've been meaning to try that!! Thank you for the suggestion :) I forgot all about that, since I just copy-pasted a template for this first prototype. But definitely will fix that soon. Yay!
